name: Trigger auto deployment for if-delivery-api-final

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ developer ]
    paths:
    - '**'
    - '.github/workflows/if-delivery-api-final-AutoDeployTrigger-e8942e54-1faf-4bb1-8f50-43b687f795c8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.IFDELIVERYAPIFINAL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IFDELIVERYAPIFINAL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IFDELIVERYAPIFINAL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.IFDELIVERYAPIFINAL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IFDELIVERYAPIFINAL_REGISTRY_PASSWORD }}
          containerAppName: if-delivery-api-final
          resourceGroup: cloud-shell-storage-eastus
          imageToBuild: eujoaomatheus/if-delivery-api-final:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


